### ISSUE TITLE
Support animated WebP

### ISSUE THREAD

**Issue by pengweiqhca** [NickeManarin/ScreenToGif#715]

**Comment by cool-delete** [comment]
+1 support 
.apng to huge

**Comment by vrubleg** [comment]
@cool-delete APNG is smaller when optimized properly. Examples: http://littlesvr.ca/apng/gif_apng_webp.html

**Comment by NickeManarin** [comment]
Done, it will be available with v2.28.

**Comment by 2DeezDev** [comment]
I can save the file as webp, but I can't open it back up. Any plans to support opening webp files?

**Comment by matyX6** [comment]
Still have the same problem @2DeezDev mentioned. The tool is great optimizing all kinds of images for websites. Shame I can't edit them after exporting.
